### ISSUE TITLE
Error with loading homepage

### ISSUE THREAD

**Issue by prondubuisi** [dkarlovi/opentelemetry-php-user-test#1]
Hello, @dkarlovi I was trying to check out this project, hence I followed the commands in the readme.md

While trying to load the index page, I get this error 
<img width="1391" alt="User Test" src="https://user-images.githubusercontent.com/22311928/106390459-dca07d80-63e8-11eb-96b5-1ddb1acae301.png">

On A closer look, there is no vendor folder in the project, I was thinking Docker was supposed to pull that in, or do I run composer install locally? 

Inbetween the Jaeger loads fine
<img width="1676" alt="Jaeger" src="https://user-images.githubusercontent.com/22311928/106390560-3b65f700-63e9-11eb-99a9-28a9e25e71a6.png">

**Comment by dkarlovi** [comment]
Run composer install locally yes.

**Comment by prondubuisi** [comment]
This, Works, I will be making a PR to add this information to the readme.md
